### ISSUE TITLE
No Transcript on Chrome When Upgraded to MacOS Monterey on MacBook Pro

### ISSUE THREAD

**Issue by DeanWronowski** [speechly/speech-recognition-polyfill#10] opened 2021-11-09 20:16 UTC
### Describe the bug
Everything has been working perfectly until I decided to upgrade Mac OS to Monterey on my Macbook Pro. 

When running the code from here https://github.com/speechly/speech-recognition-polyfill#integrating-with-react-speech-recognition. Nothing gets translated if I am using the Chrome Browser with all plugins disabled. However, when running the code in Firefox and Safari it works completely fine.

I tried the demo on the machine - https://speechly-demos.herokuapp.com/flight-booking - that does not work either.

However, when I upgraded my iMac machine to the same versions, that works completely fine which is really weird.

When I took out the polypill code, it transcribes fine on Chrome.

### To Reproduce
Load https://speechly-demos.herokuapp.com/flight-booking in Chrome on a MacBook Pro running Mac OS Monterey

### Expected behaviour
Transcript to be displayed

### Environment

- Platform: Desktop
- OS: Mac OS Monterey
- Browser Chrome
- Chrome Version: Version 95.0.4638.69 (Official Build) (x86_64)

**Comment by JamesBrill** [comment] 2021-11-09 20:48
Hi @DeanWronowski Thanks for raising the issue!

I don't have access to Monterey at the moment, but I may be able to help. I've seen some threads saying that WebSockets are broken on Monterey, at least in Safari a few months ago. Perhaps this issue in Chrome is related - it's not uncommon for this to happen in new macOS releases.

First, let me confirm my understanding of what you've observed:
* The `react-speech-recognition` example does not transcribe anything with the Speechly polyfill when running on Monterey + Chrome
* It works fine on Monterey + Safari/Firefox
* It works fine on Monterey + Chrome, but only with the polyfill turned off

So it sounds like the native Chrome speech recognition is working fine in Monterey. It's only the browser APIs that the polyfill is based on that are affected. Off the top of my head, they would be `MediaDevices`, `AudioContext`, and WebSockets.

I have two suggestions for further diagnosis:
* Try to run the example from [this library](https://github.com/speechly/speechly/tree/main/libraries/browser-client#usage), which is what this polyfill is built on. This is just to apply a process of elimination to check that this isn't related to a bug specifically in this polyfill. I would expect the `browser-client` to fail in the same way
* Could you go to the Speechly flight booking demo app and share either a screenshot or copy-paste of the network requests? Here's what to look for:
  * Open Chrome Devtools first
  * Then open https://speechly-demos.herokuapp.com/flight-booking
  * Open the Network tab in Devtools
  * Look for a WebSockets request. The URL will be something like `wss://api.speechly.com/ws/v1?languageCode=en-US&sampleRate=16000`
  * Under that request, open the Messages tab
  * Hold down the microphone button, give permission to the browser if needed, and speak
  * Note anything that looks like an error message in the Messages tab. It may help to filter these by "Receive" as there will be a lot. Also note any errors in the Console tab if you see any. Here's what it looks like on Big Sur + Chrome:
<img width="893" alt="Screen Shot 2021-11-09 at 8 42 53 PM" src="https://user-images.githubusercontent.com/2140027/141001501-3dc2f50f-1123-456c-90b9-734489192492.png">

Other questions:
* When you hold down the the microphone button, does anything unusual happen when Chrome asks you for permission to use the microphone?
* Is there any indicator that Chrome _doesn't_ have permission to use the microphone?
* Do you see the red dot on the tab to indicate that the microphone is recording?

**Comment by DeanWronowski** [comment] 2021-11-09 21:27
Very impressive reply @JamesBrill 

Yeah - your understanding of the browsers is spot on.

See attachment of the Web-socket requests when speaking on the Speechly flight booking demo app via Chrome.

<img width="1792" alt="Screenshot 2021-11-09 at 21 21 39" src="https://user-images.githubusercontent.com/3969540/141007080-926e19b0-5095-4b6a-8937-80fe3102ee33.png">

The red dot appears and I have double checked the microphone permission

<img width="155" alt="Screenshot 2021-11-09 at 21 24 39" src="https://user-images.githubusercontent.com/3969540/141007254-c45bd9b9-a741-4375-bfd5-d377825d76d2.png">

Would you like me to try the example as well now? - https://github.com/speechly/speechly/tree/main/libraries/browser-client#usage

**Comment by JamesBrill** [comment] 2021-11-09 21:52
If you click on the dropdown at the top-left of Messages where it says "All", you can filter to just "Receive" (the red entries). Then we can get rid of the "Binary Message" entries (I believe this is audio being streamed from your browser to the Speechly server) and focus on the responses. Also, can you provide a screenshot of the Console tab so we can see if there are any JavaScript errors?

From what we've seen so far:
* Chrome is getting access to the microphone
* The Speechly web client is able to stream audio to its server, at least briefly
* Something is causing the audio streaming to end prematurely
* It looks like it's the client that's initiating the stop. Unclear whether this is programmatically due to it catching some JavaScript error, or if it's something at the transport layer. For example, for me that "stopped" message is received automatically if no speech is transcribed for long enough, kind of like a server-driven timeout. The difference for me is that my client didn't initiate this by sending a "stop" message like yours did.

And yes, if you could test the `browser-client` example (checking that it fails on Chrome, but succeeds on other browsers), that would be useful. If you see the issue there, I can ask the Speechly team if they can reproduce the issue and investigate what aspect of Chrome on Monterey is affecting their web client. It might also be worth you re-raising this issue on that repo if you see the same issue there - this polyfill is just a wrapper for that library, so that's where any fix will need to be applied.

**Comment by DeanWronowski** [comment] 2021-11-10 08:02
See attachment after filtering the network requests to "Receive" on Chrome

<img width="1792" alt="Screenshot 2021-11-10 at 07 48 10" src="https://user-images.githubusercontent.com/3969540/141071619-0d72e489-7704-4870-9d05-28e338cdb219.png">

See attachment of the console. There is one request being blocked but that relates to analysis on Chrome

<img width="1791" alt="Screenshot 2021-11-10 at 07 47 49" src="https://user-images.githubusercontent.com/3969540/141071707-2eab0ac0-be6b-47c4-85aa-cab6918eabfb.png">

See attachment after filtering the network requests to "Receive" when running the browser-client code on Chrome

<img width="1792" alt="Screenshot 2021-11-10 at 07 57 21" src="https://user-images.githubusercontent.com/3969540/141072912-c51acfaf-b8c0-44b2-ba78-c0eac68abf05.png">

See attachment of the console when running the browser-client code on Chrome

<img width="1789" alt="Screenshot 2021-11-10 at 07 58 22" src="https://user-images.githubusercontent.com/3969540/141073050-91aca7e2-4bb1-403a-8eb1-3ddf86fd41e8.png">

See attachment after filtering the network requests to "Receive" on Firefox 

<img width="1690" alt="Screenshot 2021-11-10 at 08 00 23" src="https://user-images.githubusercontent.com/3969540/141073411-2b42a85d-7e2a-4de2-a88b-66a184ca9a4d.png">
when running the browser-client code.

Which repo would you like me to create this issue in? Many thanks for your help so far,

**Comment by aukkonen** [comment] 2021-11-10 09:42
Hi @DeanWronowski Thank you for reporting this!

If you could indeed file another issue at this other repo where we keep our web-related libraries, including the browser-client: https://github.com/speechly/speechly/issues
No need to make the new issue as detailed as the one here, but please add a link to this one.

Thanks!

**Comment by JamesBrill** [comment] 2021-11-28 11:41
Closing after the resolution in https://github.com/speechly/speechly/issues/77 Of course, please re-open if needed.

**Closed by JamesBrill** 2021-11-28 11:41 UTC
Labels: bug
